name: CI/CD

# 触发条件（当代码推送或创建 PR 时触发）
on:
  push:
    branches:
      - main     # 在 main 分支 push 时触发
  pull_request:
    branches:
      - main     # 在 main 分支创建 PR 时触发

# 定义工作流的作业
jobs:
  CI:
    runs-on: ubuntu-latest  # 使用的运行环境，可以是 Ubuntu、Windows、macOS

    steps:
      # 检出代码到运行器
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 安装依赖
      - name: Install dependencies
        run: npm install pnpm -g && pnpm install

      # 构建项目
      - name: Build project
        run: pnpm run build

  CD:
    needs: CD  # 依赖 build 作业的成功执行
    runs-on: ubuntu-latest

    steps:
      # 检出代码到运行器
      - name: Checkout code
        uses: actions/checkout@v3

      # 使用 SSH 部署到服务器
      - name: Upload to Deploy Server
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          # SSH_PRIVATE_KEY为准备工作步骤三中生成密钥对里的私钥
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # 指定当前目录中要上传的内容
          SOURCE: ".output/"
          # 指定上传到部署机器的哪个目录下
          TARGET: "~/apps/yuzu-tea"
          # 上传前指令，此处用于清空TARGET下的文件
          ARGS: "-avzr --delete"
          # SSH_HOST为机器的公网IP
          REMOTE_HOST: ${{ secrets.SSH_HOST}}
          # SSH_USER为登录机器时用到账号名
          REMOTE_USER: ${{ secrets.SSH_USER }}
