name: Front-end CI/CD

# 触发条件（当代码推送或创建 PR 时触发）
on:
  push:
    branches:
      - main     # 在 main 分支 push 时触发
  pull_request:
    branches:
      - main     # 在 main 分支创建 PR 时触发

# 定义工作流的作业
jobs:
  build:
    runs-on: ubuntu-latest  # 使用的运行环境，可以是 Ubuntu、Windows、macOS

    steps:
      # 检出代码到运行器
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 安装依赖
      - name: Install dependencies
        run: npm install pnpm -g && pnpm install

      # 构建项目
      - name: Build project
        run: pnpm run build

  deploy:
    needs: build  # 依赖 build 作业的成功执行
    runs-on: ubuntu-latest

    steps:
      # 检出代码到运行器
      - name: Checkout code
        uses: actions/checkout@v3

      # 使用 SSH 部署到服务器
      - name: Deploy to Server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./output/  # 本地构建后的文件夹路径
          target: ~/apps/yuzu-tea  # 服务器上的部署路径
